### ISSUE TITLE
Avslutte A3U

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/utbredelse#3]
- [x] Innarbeiding av innspill fra tjenesteeiere; --> Håndteres i #5
- [x] Leveranser og innspill til Årsmøtet; --> Håndteres i #4 og #71

- [x] Rettskriving mv.; --> Håndteres i #5

- [x] Avslutte A3U Vedlegg 4 Strategi, Vedlegg 5 Piloter og tilltak --> Håndteres i #52

**Comment by acn-martinn** [comment]
Forslag til agenda fra LV:
1. Gjennomgang av interessentanalyse og strategi
2. Innsendte spørsmål mv.

Innspill til agendaendring: 
- [ ] Siste frist for innspill

**Comment by lvbachmann** [comment]
Settes til done da alt reelt arbeid er identifisert og håndteres i separate issues.

**Comment by lvbachmann** [comment]
Alle planlagte oppgaver utført. Lukkes.
