### ISSUE TITLE
Migreringsplan: SSB

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/utbredelse#6]
- [x] Martin kaller inn til team-møte
- [x]  Gå igjennom smørbrødsliste som mottatt tidligere
- [ ]  Ønsker informasjon om forskjellig funksjonalitet som kan utføres på nye måter, **preutfylling, og abbonement**
- [x] Kalle inn til oppfølgingsmøte og videre dialog for etablering;

- [ ] Lage migreringsplan for SSB;

- [x] Sette opp møte for gjennomgang av deres tjenesteexcel;

- [ ] Generalisere og oppdatere tjenestekriterier for vurdering

- [ ] Produktifisering av materialet
