### ISSUE TITLE
Design and create a video for use in marketing - what to use Altinn Studio for

### ISSUE THREAD

**Issue by lvbachmann** [Altinn/utbredelse#73]
> **Merk:** Arvet fra Altinn Studio-boardet

## Description
Produce a video that shows the whole process of creating a digital service. Visualize that someone has a need/idea, define user needs, create the service and finally show that a person is using the service on a tablet or mobile.

## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
Input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria

...

## Tasks
- [ ] Identify the goal(s) for the video
- [ ] Write a storyboard and script to outline and visualize what we plan to show
- [ ] Review/test of storyboard 
- [ ] Record the video
- [ ] User-test
- [ ] Publish/Share

## Specification tasks
- [ ] Test design / decide test need

## Development tasks
- [ ] Documentation (if relevant)
- [ ] Manual test (if needed)
- [ ] Automated test (if needed)
